package LexicalSeparator;

public enum TokenType {
    DATATYPE, NUMBERS, IDENTIFIER, KEYWORD,
    ARITH_OPERATOR, ASSIGNMENT_OPERATOR, COMPARISON_OPERATOR, REL_OPERATOR, LOGIC_OPERATOR,
    SEMICOLON, OPENPARENTHESIS, CLOSEPARENTHESIS, OPENBRACKET, CLOSEBRACKET, OPENBRACE, CLOSEBRACE, COMMA,
    STRING_LITERAL, SYMBOL, SIGN
}
