package LexicalSeparator;

public enum TokenType {
    DATATYPE, VARIABLENAME, NUMBERS,
    ARITH_OPERATOR, ASSIGNMENT_OPERATOR, COMPARISON_OPERATOR, REL_OPERATOR, LOGIC_OPERATOR, KEYWORD,
    SEMICOLON, OPENPARENTHESIS, CLOSEPARENTHESIS, OPENBRACKET, CLOSEBRACKET, OPENBRACE, CLOSEBRACE,
    STRING_LITERAL, SYMBOL, SIGN, ARRVAL
}
